name: DisplayAuctionHouse
version: ${project.version}
main: io.github.henrique02w.displayauctionhouse.DisplayAuctionHouse
api-version: "26.2"
description: Auction House com displays fisicos no mundo
authors: [ Henrique02W ]
website: https://github.com/Henrique02W/DisplayAuctionHouse
softdepend:
  - Vault

commands:
  dah:
    description: Comando principal do DisplayAuctionHouse 
    usage: /dah <subcommand>
    aliases: [ auctionhouse, ah ]

permissions:
  dah.admin:
    description: Permissão de admin do DisplayAuctionHouse
    default: op
    children:
      dah.sell: true
      dah.buy: true
      dah.inbox: true
  dah.sell:
    description: Permissão de player para vender
    default: true
  dah.buy:
    description: Permissão de player para comprar
    default: true
  dah.inbox:
    description: Permissão de player para acessar o correio
    default: true
