name: DisplayAuctionHouse
version: '1.0.0'
main: com.displayah.DisplayAuctionHouse
api-version: '1.21'
description: Auction House com display fisico no mundo
authors: [ Henrique02W ]
softdepend:
  - Vault

commands:
  dah:
    description: Comando principal do DisplayAuctionHouse 
    usage: /dah <subcommand>
    aliases: [ auctionhouse, ah ]

permissions:
  dah.admin:
    description: Permissão de admin do DisplayAuctionHouse
    default: op
  dah.sell:
    description: Permissão de player para vender
    default: true
  dah.buy:
    description: Permissão de player para comprar
    default: true
  dah.inbox:
    description: Permissão de player para acessar o correio
    default: true
